### ISSUE TITLE
As a guest user, I want to be able to log in to the game with my chosen credentials (i.e., username) to play the game.

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#1]
**Acceptance criteria:** 

- [x] sopra-fs24-group-46/server#15
- [x] sopra-fs24-group-46/client#3
- [x] sopra-fs24-group-46/server#17
- [x] sopra-fs24-group-46/server#18
