### ISSUE TITLE
Question: As a player, I would like to read the entity I need to place on the map, to prepare for my response. 

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#10]
**Acceptance criteria:** 
- [x] sopra-fs24-group-46/client#21
- [x] sopra-fs24-group-46/server#48
- [x] sopra-fs24-group-46/server#49

**Comment by S3r4f1n** [comment]
Closing since all tasks are done
