### ISSUE TITLE
As a player, I want to locate where the lake or mountain is before the time runs out or before everyone guesses to get my points

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#11]
**Acceptance criteria:** 
- [ ] sopra-fs24-group-46/client#22
- [x] sopra-fs24-group-46/server#51
- [x] sopra-fs24-group-46/server#52
- [ ] sopra-fs24-group-46/server#53
