### ISSUE TITLE
Leaderboard: As a player, I want to see the leaderboard of the current game (cumulative scores). To see how good and oder players are (see progress). 

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#12]
**Acceptance criteria:** 
- [x] sopra-fs24-group-46/client#23
- [x] sopra-fs24-group-46/server#55
- [x] sopra-fs24-group-46/client#24
- [x] sopra-fs24-group-46/client#64
- [x] sopra-fs24-group-46/client#65
- [X] sopra-fs24-group-46/client#62

**Comment by S3r4f1n** [comment]
Transferred task sopra-fs24-group-46/client#25 to M4.
