### ISSUE TITLE
M4: During development, Tasks came up which were not planned. To avoid adding Sprint 2 Tasks to Sprint 1 Userstories we add them here. (Tasks for M4 which came up during M3)

### ISSUE THREAD

**Issue by S3r4f1n** [sopra-fs24-group-46/server#126]
**Acceptance Criteria**
- [x] sopra-fs24-group-46/server#124
- [x] sopra-fs24-group-46/client#82 (Bug fixes and improvements)
- [x] sopra-fs24-group-46/client#78
- [x] sopra-fs24-group-46/client#80
- [x] #72 
- [x] sopra-fs24-group-46/client#77
- [x] sopra-fs24-group-46/client#76

**Comment by S3r4f1n** [comment]
Closing since all tasks are done
