### ISSUE TITLE
Refactoring: As developers we need clean code to keep working. In M3 alot of code was written wich is no longer used or could be simplyfied.

### ISSUE THREAD

**Issue by S3r4f1n** [sopra-fs24-group-46/server#127]
**Acceptance Criteria**
- [x] sopra-fs24-group-46/client#83
- [x] sopra-fs24-group-46/client#74
- [x] sopra-fs24-group-46/client#71
- [x] sopra-fs24-group-46/client#75
- [x] sopra-fs24-group-46/client#70
- [x] sopra-fs24-group-46/client#72
- [x] sopra-fs24-group-46/client#73
- [x] sopra-fs24-group-46/client#81
- [x] sopra-fs24-group-46/client#101
- [x] #131

**Comment by S3r4f1n** [comment]
Closing since all tasks are done
