### ISSUE TITLE
End View: As a player, once all the rounds are finished, I should be able to see the final leaderboard to visualize the winner and to be able to return to my profile page

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#13]
**Acceptance criteria:** 
- [x] sopra-fs24-group-46/client#2
- [x] sopra-fs24-group-46/client#26
- [x] sopra-fs24-group-46/client#27
- [x] sopra-fs24-group-46/client#28
- [x] sopra-fs24-group-46/client#29
- [x] sopra-fs24-group-46/client#68

**Comment by RoVi80** [comment]
Closed in client

**Comment by RoVi80** [comment]
Closing since all tasks are done
