### ISSUE TITLE
As an unregistered user, if I want to create an account, I want to be able to register as a user with my chosen credentials, to access information/features that are exclusive to registered users

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#2]
**Acceptance criteria:** 
- [ ] sopra-fs24-group-46/client#4
- [x] sopra-fs24-group-46/server#20
- [ ] sopra-fs24-group-46/client#5
- [x] sopra-fs24-group-46/server#22
- [x] sopra-fs24-group-46/server#23
