### ISSUE TITLE
As a registered user, I want to be able to log in to the game with my chosen credentials to play the game. 

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#3]
**Acceptance criteria:** 
- [ ] sopra-fs24-group-46/client#6
- [ ] sopra-fs24-group-46/client#7
- [ ] sopra-fs24-group-46/server#26
- [ ] sopra-fs24-group-46/client#8

**Comment by RoVi80** [comment]
https://github.com/sopra-fs24-group-46/client/commit/972505d6f2e08ed22a62a83fc108b119beeb3801
