### ISSUE TITLE
As a registered user, I want to create/host a new game which other people can join via pin code, in order to play with my peers. 

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#5]
**Acceptance criteria:** 
- [ ] sopra-fs24-group-46/client#1
- [ ] sopra-fs24-group-46/server#31
- [ ] sopra-fs24-group-46/client#10
- [ ] sopra-fs24-group-46/client#11
