### ISSUE TITLE
As a host, I want to be able to specify the game settings to set the game specifications

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#6]
**Acceptance criteria:** 
- [x] sopra-fs24-group-46/client#12
- [x] sopra-fs24-group-46/server#35
- [x] sopra-fs24-group-46/server#36

**Comment by S3r4f1n** [comment]
Bug with guessing time per round.
Guessing time per round is not updated.
