### ISSUE TITLE
Lobby: As a host, I want to be able to visualize the players joining the lobby and the specifications once the game settings are set, to start the game

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#7]
**Acceptance criteria:** 
- [x] sopra-fs24-group-46/server#37
- [x] sopra-fs24-group-46/client#13
- [x] sopra-fs24-group-46/client#14
- [x] sopra-fs24-group-46/client#67

**Comment by S3r4f1n** [comment]
Closed in: 0012f3dae

**Comment by S3r4f1n** [comment]
Closing since all tasks are done. Transferred on task (Closing Lobby kicks all players) to Lobby Leave. Since it is not high priority
