### ISSUE TITLE
PowerUp x2: As a player, I want to activate a times two Power-Up which doubles the points I gain for this round.

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#78]
- [x] sopra-fs24-group-46/server#80
- [x] sopra-fs24-group-46/server#83
- [x] sopra-fs24-group-46/client#44
- [x] sopra-fs24-group-46/client#45
- [x] sopra-fs24-group-46/client#46

**Comment by S3r4f1n** [comment]
Closed since all tasks are done
