### ISSUE TITLE
As a user that wants to play, I want to be able to join a game by typing in the game code to play with other users  

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#8]
**Acceptance criteria:** 
- [ ] sopra-fs24-group-46/client#16
- [ ] sopra-fs24-group-46/client#17
- [ ] sopra-fs24-group-46/client#18

**Comment by S3r4f1n** [comment]
Closed with: 5d2e8188
