### ISSUE TITLE
Power Up Shield: As a player, I want to activate a Shield Power Up. Which I activate when I have no. For one round, I get average points. Instead of the points from my guess.

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#84]
- [x] sopra-fs24-group-46/server#86
- [x] sopra-fs24-group-46/server#89
- [x] sopra-fs24-group-46/client#44
- [x] sopra-fs24-group-46/client#45
- [x] sopra-fs24-group-46/client#46
